import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Nav from "@/components/nav";
import CurrentSectionContextProvider from "@/context/currentSectionContext";
import { ParallaxProvider } from "react-scroll-parallax";
import { Providers } from "@/lib/providers";

const inter = Inter({ subsets: ["latin"] });

const nunito_sans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${nunito_sans.className}  text-white relative bg-gradient-to-b from-[#010208]  to-[#000517]`}
      >
        <Providers>
          <Nav />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
